### ISSUE TITLE
Backend API throws error

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure-Samples/openhack-devops-proctor#66]
When I connect to the sentinel, the backend API cause an error.  You can find the error Function App > ReportStatus > Monitor

It seems  this query's problem. 

https://github.com/Azure-Samples/openhack-devops-proctor/blob/master/leaderboard/api/SharedLibrary/DocumentService.cs#L65

```
Report Status error: One or more errors occurred. (Message: {"Errors":["Resource Not Found"]}

ActivityId: dc364408-5652-4afd-8f8a-7c4ee5a881e8, Request URI: /apps/f4533d11-81e3-4512-b639-0f0475c10611/services/485c4926-761b-4051-b95f-605fa1863a08/partitions/919d9245-cd4b-434e-8702-c5dffd4f43c8/replicas/131729235082120966s, RequestStats: 

ResponseTime: 2018-06-11T13:47:36.2527324Z, StoreReadResult: StorePhysicalAddress: rntbd://10.0.0.26:11000/apps/f4533d11-81e3-4512-b639-0f0475c10611/services/485c4926-761b-4051-b95f-605fa1863a08/partitions/919d9245-cd4b-434e-8702-c5dffd4f43c8/replicas/131729235082120966s, LSN: 56, GlobalCommittedLsn: 56, PartitionKeyRangeId: , IsValid: True, StatusCode: 0, IsGone: False, IsNotFound: True, IsInvalidPartition: False, RequestCharge: 1, ItemLSN: -1, ResourceType: Collection, OperationType: Read

ResponseTime: 2018-06-11T13:47:36.2527324Z, StoreReadResult: StorePhysicalAddress: rntbd://10.0.0.25:13700/apps/f4533d11-81e3-4512-b639-0f0475c10611/services/485c4926-761b-4051-b95f-605fa1863a08/partitions/919d9245-cd4b-434e-8702-c5dffd4f43c8/replicas/131729992147376218s, LSN: 56, GlobalCommittedLsn: 56, PartitionKeyRangeId: , IsValid: True, StatusCode: 0, IsGone: False, IsNotFound: True, IsInvalidPartition: False, RequestCharge: 1, ItemLSN: -1, ResourceType: Collection, OperationType: Read

, SDK: Microsoft.Azure.Documents.Common/2.0.0.0)
```

```
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)

   at System.Threading.Tasks.Task`1.get_Result()

   at Microsoft.Azure.Documents.Linq.DocumentQuery`1.<GetEnumerator>d__25.MoveNext()

   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)

   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)

   at Services.DocumentService.<GetServiceAsync>d__6`1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Leaderboard.RestAPI.<ReportStatus>d__5.MoveNext() in /home/azureuser/openhack-devops-proctor/leaderboard/api/Leaderboard/RestAPI.cs:line 51
```

**Comment by TsuyoshiUshio** [comment]
This error is fixed by the pull request. 
https://github.com/Azure-Samples/openhack-devops-proctor/pull/68
Please have a look.
